set (INIT_SCRIPT_PATH ${CMAKE_CURRENT_LIST_DIR})
set (SUDODEVD_SERVICE sudodevd.service)
set (SUDODEVD_CONF sudodevd.conf)
set (SUDODEVD sudodevd)
set (RC_SUDODEVD rc.sudodevd)
set (SYSTEMD_DIR ${CMAKE_INSTALL_PREFIX}/lib/systemd/system)
set (UPSTART_DIR ${CMAKE_INSTALL_PREFIX}/../etc/init)
set (SYSVINIT_DIR ${CMAKE_INSTALL_PREFIX}/../etc/init.d)
set (BSDINIT_DIR ${CMAKE_INSTALL_PREFIX}/../etc/rc.d)
set (SYSTEMD_SCRIPT ${INIT_SCRIPT_PATH}/systemd/${SUDODEVD_SERVICE})
set (UPSTART_SCRIPT ${INIT_SCRIPT_PATH}/upstart/${SUDODEVD_CONF})
set (SYSVINIT_SCRIPT ${INIT_SCRIPT_PATH}/sysv/${SUDODEVD})
set (BSDINIT_SCRIPT ${INIT_SCRIPT_PATH}/bsd/${RC_SUDODEVD})
set (SYS_SYSTEMD_DIR /usr/lib/systemd/system)
set (SYS_UPSTART_DIR /etc/init)
set (SYS_SYSVINIT_DIR /etc/init.d)
set (SYS_BSDINIT_DIR /etc/rc.d)

if (IS_DIRECTORY ${SYS_SYSTEMD_DIR})
  execute_process (COMMAND install -dv ${SYSTEMD_DIR})
  execute_process (COMMAND install -Dv -m0644 ${SYSTEMD_SCRIPT} ${SYSTEMD_DIR})
  if (EXISTS ${SYS_SYSTEMD_DIR}/${SUDODEVD_SERVICE})
    execute_process (COMMAND systemctl daemon-reload)
    execute_process (COMMAND systemctl enable sudodevd.service)
    execute_process (COMMAND systemctl restart sudodevd.service)
  endif ()
elseif (IS_DIRECTORY ${SYS_UPSTART_DIR})
  execute_process (COMMAND install -dv ${UPSTART_DIR})
  execute_process (COMMAND install -Dv -m0644 ${UPSTART_SCRIPT} ${UPSTART_DIR})
  if (EXISTS ${SYS_UPSTART_DIR}/${SUDODEVD_CONF})
    execute_process (COMMAND initctl reload-configuration)
    execute_process (COMMAND initctl restart sudodevd)
  endif ()
elseif (IS_DIRECTORY ${SYS_SYSVINIT_DIR})
  execute_process (COMMAND install -dv ${SYSVINIT_DIR})
  execute_process (COMMAND install -Dv -m0644 ${SYSVINIT_SCRIPT} ${SYSVINIT_DIR})
  if (EXISTS ${SYS_SYSVINIT_DIR}/${SUDODEVD})
    foreach (level RANGE 2 5)
      execute_process (COMMAND ln -sv ${SYS_SYSVINIT_DIR}/${SUDODEVD} /etc/rc${level}.d/S60${SUDODEVD})
    endforeach ()
    foreach (level 0 1 6)
      execute_process (COMMAND ln -sv ${SYS_SYSVINIT_DIR}/${SUDODEVD} /etc/rc${level}.d/K60${SUDODEVD})
    endforeach ()
    execute_process (COMMAND chmod -v 755 ${SYS_SYSVINIT_DIR}/${SUDODEVD})
    execute_process (COMMAND ${SYS_SYSVINIT_DIR}/${SUDODEVD} start)
  endif ()
elseif (IS_DIRECTORY ${SYS_BSDINIT_DIR})
  execute_process (COMMAND install -dv ${BSDINIT_DIR})
  execute_process (COMMAND install -Dv -m0644 ${BSDINIT_SCRIPT} ${BSDINIT_DIR})
  if (EXISTS ${SYS_BSDINIT_DIR}/${RC_SUDODEVD})
    message (STATUS "It seems you are using BSD init.")
    message (STATUS "You have to write lines in suitable location of files manually to set start/stop runlevels:")
    message (STATUS "")
    message (STATUS "For ${SYS_BSDINIT_DIR}/rc.4 and ${SYS_BSDINIT_DIR}/rc.M:")
    message (STATUS "[ -x ${SYS_BSDINIT_DIR}/${RC_SUDODEVD} ] && ${SYS_BSDINIT_DIR}/${RC_SUDODEVD} start")
    message (STATUS "")
    message (STATUS "For ${SYS_BSDINIT_DIR}/rc.0, ${SYS_BSDINIT_DIR}/rc.6 and ${SYS_BSDINIT_DIR}/rc.K:")
    message (STATUS "[ -x ${SYS_BSDINIT_DIR}/${RC_SUDODEVD} ] && ${SYS_BSDINIT_DIR}/${RC_SUDODEVD} stop")
    message (STATUS "")
    execute_process (COMMAND "chmod -v 755 ${SYS_BSDINIT_DIR}/${RC_SUDODEVD}")
    execute_process (COMMAND "${SYS_BSDINIT_DIR}/${RC_SUDODEVD} start")
  endif ()
endif ()

if (${CMAKE_INSTALL_PREFIX} STREQUAL /usr)
  execute_process (COMMAND stat -c %U ${CMAKE_CURRENT_LIST_DIR} OUTPUT_VARIABLE USER OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process (COMMAND gpasswd -a ${USER} sudodev)
endif ()

